name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Remove conflicting Clang versions
      run: sudo rm -rf /usr/lib/llvm-*
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 21
    - name: Check clang version
      run: clang++ --version
    - uses: actions/checkout@v6
    - name: Install prerequisites
      run: sudo apt-get install libecm-dev gmp-ecm libgcc-14-dev
    - name: make
      run: make yafu -f Makefile.clang ICELAKE=1 ECM=1 VBITS=256 USE_SSE41=1 USE_AVX2=1 USE_BMI2=1
    - uses: actions/upload-artifact@v6
      with:
        name: Yafu
        path: yafu
