name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Uninstall conflicting toolchains
      run: |
        sudo apt-get --purge remove 'gcc-*' 'g++-*' 'clang*'
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 21
    - name: Check clang version
      run: clang++ --version
    - name: Override /usr/bin/ld
      run: |
        sudo rm /usr/bin/ld
        sudo ln -s /usr/lib/llvm-21/bin/ld /usr/bin/ld
    - uses: actions/checkout@v6
    - name: Install GMP-ECM
      run: sudo apt-get install libecm-dev gmp-ecm
    - name: make
      run: make yafu -f Makefile.clang ICELAKE=1 ECM=1 VBITS=256 USE_SSE41=1 USE_AVX2=1 USE_BMI2=1
    - uses: actions/upload-artifact@v6
      with:
        name: Yafu
        path: yafu
